server:
  port: 8080
  error:
    path: /error

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  session:
    jdbc:
      initialize-schema: always

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/composerdesk}
    username: ${DB_USERNAME:agona}
    password: ${DB_PASSWORD:qwerty}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: composer-files